name: PrimeSeller
version: '2.4.7'
main: me.byteswing.primeseller.PrimeSeller
api-version: 1.13
depend: [ Vault ]
softdepend: [ PlaceholderAPI ]
commands:
  seller:
    aliases:
      - 'sell'
      - 'buyer'
  PrimeSeller:
    aliases:
      - 'psell'