time-zone: "GMT+3" # GMT+3 стандарт

metrics: true # метрика плагина

middle-click-sell-all: true # продажа на среднюю кнопку мыши. Если false продаётся через ШИФТ+ЛКМ

enable-permission: false # включить ли право на использование команды? primeseller.open

understating-price:
  enable: true
  percent: 0,5 # на сколько % будет понижаться цена при продаже
  min-percent: 50 # минимальный % от суммы.

time-format: 'hhч. mmм. ssс.'

messages:
  sell-inventory: '#5637bc&lS#623ec9&lE#6e44d7&lL#7a4be4&lL#8651f2&lE#9258ff&lR #b9b9b9| #ddddddВы успешно продали &eсвой инвентарь. #ddddddРезультаты продажи: &e%amount% #ddddddза #53fb31$%price%!'
  sell: '#5637bc&lS#623ec9&lE#6e44d7&lL#7a4be4&lL#8651f2&lE#9258ff&lR #b9b9b9| #ddddddВы успешно продали &e%item% %amount% #ddddddза #53fb31$%price%!'
  limit: '#5637bc&lS#623ec9&lE#6e44d7&lL#7a4be4&lL#8651f2&lE#9258ff&lR #b9b9b9| #ff4141Ваш лимит на продажу этого предмета исчерпан! Приходите в другой раз.'
  amount: '#5637bc&lS#623ec9&lE#6e44d7&lL#7a4be4&lL#8651f2&lE#9258ff&lR #b9b9b9| #ff4141Недостаточно предметов.'
  limited-update-cast: # чтобы отключить уберите строки и оставьте это пустым
    - ''
    - '#ddddddСкупщик с лимитом обновился! - #00d328/seller'
    - ''
  unlimited-update-cast: # чтобы отключить уберите строки и оставьте это пустым
    - ''
    - '#ddddddСкупщик без лимита обновился! - #00d328/seller'
    - ''
  update-cast: # чтобы отключить уберите строки и оставьте это пустым
    - ''
    - '#ddddddСкупщик полностью обновился! - #00d328/seller'
    - ''

  commands:
    permission: '#5637bc&lS#623ec9&lE#6e44d7&lL#7a4be4&lL#8651f2&lE#9258ff&lR #b9b9b9| #ff4141У Вас нет прав.'
    reload: '&aКонфигурация успешно перезагружена!'
    update: '#5637bc&lS#623ec9&lE#6e44d7&lL#7a4be4&lL#8651f2&lE#9258ff&lR #b9b9b9| #00d328Список продаваемых предметов успешно обновлен!'
    added: '#5637bc&lS#623ec9&lE#6e44d7&lL#7a4be4&lL#8651f2&lE#9258ff&lR #b9b9b9| #ddddddПредмет #eaff43%item% #ddddddуспешно добавлен в список товаров. Его цена колеблится от #53fb31$%min-price% #ddddddдо #53fb31$%max-price%#dddddd за штуку.'
    addlimited-use: '&cИспользование: /primeseller addlimited (мин. цена) (макс. цена) за шт. (Держите предмет в руке) - Добавить предмет в продажу.'
    addunlimited-use: '&cИспользование: /primeseller addunlimited (мин. цена) (макс. цена) за шт. (Держите предмет в руке) - Добавить предмет в продажу.'
    update-use: '&cИспользование: /primeseller update - Обновить список торгов'