name: PrimeSeller
version: '2.5.0'
main: ru.destroy.primeseller.PrimeSeller
api-version: 1.13
softdepend: [ Vault, PlaceholderAPI ]
folia-supported: true
commands:
  seller:
    aliases:
      - 'sell'
      - 'buyer'
  PrimeSeller:
    aliases:
      - 'psell'